- proposals/info.yml
Remove HTML tags for the columns `proposal_title` and `proposal_body`.
See example here : https://metabase.osp.dev/model/917-propositions
> Correct display of title and body for proposals

- comments/info.yml
- components/info.yml
- components/locales/en.yml
Link to request : https://metabase.osp.cat/model/1208-meta-composants/query
> Components request

- comments/info.yml
- components/info.yml
- organizations/info.yml
- proposals/info.yml
Update cards to work correctly with dashboard automation
> Update cards' info.yml

- endorsements/info.yml
- endorsements/locales/en.yml
Link to meta : https://metabase.osp.cat/model/1271-meta-endorsements
> Add endorsement feature

- comments/info.yml
- proposals/info.yml
- users/info.yml
All modified request are based on this collection : https://metabase.osp.cat/collection/143-meta-tours
> Rebase all requests on related models

- forms/info.yml
- forms/locales/en.yml
- forms_answers/info.yml
- forms_answers/locales/en.yml
Link to forms : https://metabase.osp.cat/model/1428-forms
Link to forms answers : https://metabase.osp.cat/model/1424-forms-answers
> Add forms and forms answers

- blogs_posts/info.yml
- blogs_posts/locales/en.yml
Link to request : https://metabase.osp.cat/question/1496-blogs-posts
Closes #28
> Add blogs posts

- debates/info.yml
- debates/locales/en.yml
Link to request : https://metabase.osp.cat/model/1482-meta-debates
Closes #27 
Verify debates : https://participer.loire-atlantique.fr/processes/portdelaturballe/f/83/
> Add debates

- blogs_posts/info.yml
- budgets_projects/info.yml
- debates/info.yml
- meetings/info.yml
- proposals/info.yml
> Fix HTML entities removal

- blogs_posts/info.yml
- comments/info.yml
- components/info.yml
- debates/info.yml
- endorsements/info.yml
- forms/info.yml
- forms_answers/info.yml
- meetings/info.yml
- proposals/info.yml
- proposals_votes/info.yml
- users/info.yml
> Refactor dependencies in info.yml files

- blogs_posts/info.yml
- comments/info.yml
- components/info.yml
- debates/info.yml
- meetings/info.yml
- proposals/info.yml
> Rename pp to ps

- endorsements/info.yml
> Add decidim_component_id to endorsements

- forms/info.yml
> Add URL and title to forms

- users/info.yml
> Add URL to user request

- components/info.yml
> Switch from ps_participatory_space_type to ps_type

- initiatives_votes/info.yml
- initiatives_votes/locales/en.yml
closes #60 
See request here : https://metabase.osp.cat/question/1816-initiatives-votes
> Add initiatives votes

- initiatives/info.yml
- initiatives/locales/en.yml
- initiatives_votes/info.yml
- initiatives_votes/locales/en.yml
closes #59 
See request here : https://metabase.osp.cat/model/1815-initiatives
> Add initiatives

- organizations/info.yml
> Remove HTML from description of organization

- budgets/info.yml
- budgets/locales/en.yml
- budgets/locales/fr.yml
> Add URL and ps_slug to budgets

- projects_votes/info.yml
- projects_votes/locales/en.yml
- projects_votes/locales/fr.yml
> Add vote_finished

- initiatives/info.yml
> Remove ? in Postres queries

- proposals/info.yml
- proposals/locales/en.yml
- proposals/locales/fr.yml
> Add comments_count and endorsements_count to proposals

- forms_answers/info.yml
- meetings/info.yml
> Move from || to concat

- forms_answers/info.yml
- forms_answers/locales/en.yml
- forms_answers/locales/fr.yml
> Add IP hash column

- budgets_projects/info.yml
- budgets_projects/locales/en.yml
- budgets_projects/locales/fr.yml
> Add created_at to projects

- categorizations/info.yml
- categorizations/locales/en.yml
- categorizations/locales/fr.yml
> Unnest categorizations and rename name column

- participations/info.yml
> Convert session_token into usable id for participants counting

- proposals/info.yml
> Add state filtering to proposals
